### Reading & Writing Excel Files with Python

#### Documentation: 
https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

#### Notebook by Bryan Cafferky, Copyright 2022

For demonstration only. Not intended for production.

#### Code Example 01 - Read an Excel file...

In [8]:
import pandas as pd

pd.read_excel('250_most_frequent_german_words_danish.xlsx')

      ID Question       Answer  Box  Last Review  Next Review
0      1  den/det  der/die/das    1            0            0
1      2       og          und    1            0            0
2      3      til           zu    1            0            0
3      4       af          von    1            0            0
4      5       en          ein    1            0            0
..   ...      ...          ...  ...          ...          ...
192  193    punkt        punkt    1            0            0
193  194      mor       mutter    1            0            0
194  195   verden         welt    1            0            0
195  196      nær          nah    1            0            0
196  197    bygge        bauen    1            0            0

[197 rows x 6 columns]

#### Code Example 02 - Read an Excel file into a pandas dataframe...

In [9]:
df_leitner = pd.read_excel('250_most_frequent_german_words_danish.xlsx', index_col=0)
df_leitner.head(3)

   Question       Answer  Box  Last Review  Next Review
ID
1   den/det  der/die/das    1            0            0
2        og          und    1            0            0
3       til           zu    1            0            0

In [14]:
def move_card_right(df, card_id):
    if df.at[card_id, "Box"] < 5:  # max box
        df.at[card_id, "Box"] += 1

def move_card_left(df, card_id):
    if df.at[card_id, "Box"] > 1:  # min box
        df.at[card_id, "Box"] -= 1

In [ ]:
from datetime import datetime

today = pd.Timestamp(datetime.today().date())
due_cards = df[df["Next Review"] <= today]

In [15]:
df["Box"] = df["Box"].astype(int)

NameError: name 'df' is not defined

#### Code Example 03 - Read a sheet within an Excel file into a dataframe...

In [33]:
df_sales = pd.read_excel('DimGeography.xlsx', sheet_name='salessheet', index_col=1)  
df_sales

            StoreID State  Year    Sales
City
Providence        1    RI  2015  1200000
Boston            2    MA  2015  4000000
Bangor            3    ME  2015  2300000
Portsmouth        4    NH  2015  1200000
New York          5    NY  2015   589000
Nashville         6    TN  2015  1350000
Harttford         7    CT  2015  3240000

#### Code Example 04 - Read a sheet within an Excel file into a dataframe, renaming columns.

In [34]:
df_sales2 = pd.read_excel('DimGeography.xlsx', sheet_name='salessheet', index_col=None, names=['A','B','C','D', 'E'])   
df_sales2

   A           B   C     D        E
0  1  Providence  RI  2015  1200000
1  2      Boston  MA  2015  4000000
2  3      Bangor  ME  2015  2300000
3  4  Portsmouth  NH  2015  1200000
4  5    New York  NY  2015   589000
5  6   Nashville  TN  2015  1350000
6  7   Harttford  CT  2015  3240000

#### Code Example 05 - Save dataframe to an Excel file.

#### Save data back to Excel...
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html

In [35]:
df_sales.to_excel('mysales.xlsx')

In [36]:
ls *.xlsx

 Volume in drive D is DATADRIVE0
 Volume Serial Number is E6D7-EDE3

 Directory of D:\DocumentsD\Presentations\PythonDataSources\PythonExcel

06/05/2022  10:11 AM            52,707 DimGeography.xlsx
06/05/2022  06:15 PM             5,716 mysales.xlsx
               2 File(s)         58,423 bytes
               0 Dir(s)  420,416,573,440 bytes free

#### Code Example 06 - Save dataframe to a sheet within an Excel file.

In [37]:
df_sales.to_excel('mysales.xlsx',sheet_name='secondsheet',index=False)

In [38]:
ls *.xlsx

 Volume in drive D is DATADRIVE0
 Volume Serial Number is E6D7-EDE3

 Directory of D:\DocumentsD\Presentations\PythonDataSources\PythonExcel

06/05/2022  10:11 AM            52,707 DimGeography.xlsx
06/05/2022  06:15 PM             5,622 mysales.xlsx
               2 File(s)         58,329 bytes
               0 Dir(s)  420,385,415,168 bytes free

#### Save data as CSV...
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

#### Code Example 07 - Save dataframe to a CSV file.

In [39]:
df_sales.to_csv("mysles.csv", index=False)

In [40]:
ls *.csv

 Volume in drive D is DATADRIVE0
 Volume Serial Number is E6D7-EDE3

 Directory of D:\DocumentsD\Presentations\PythonDataSources\PythonExcel

06/05/2022  06:17 PM               158 mysles.csv
               1 File(s)            158 bytes
               0 Dir(s)  420,323,516,416 bytes free